# Ejercicio 1: Preparación de Datos

El script debe contener una sección de preparación de los datos:

1. Cargar el dataset Adult. Consultar en https://archive.ics.uci.edu/dataset/2/adult
2. Identificar y separar las variables numéricas y categóricas.
3. Realizar un análisis descriptivo.
4. Decidir qué tratamiento darle a valores faltantes.

In [2]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

# Obtener el dataset "Adult" (id=2)
adult = fetch_ucirepo(id=2)

# Data como DataFrames de pandas
X = adult.data.features
y = adult.data.targets

df = pd.concat([X, y], axis=1)

df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

## Clasificación de variables

In [3]:
from IPython.display import display
import pandas as pd

data = {'Variable': ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex',
                     'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income' ],
        'Tipo': ['cuantitativa discreta', 'cualitativa nominal', 'cuantitativa discreta', 'cualitativa ordinal', 'cuantitativa discreta', 'cualitativa nominal',
                 'cualitativa nominal', 'cualitativa nominal', 'cualitativa nominal', 'cualitativa nominal', 'cuantitativa continua', 'cuantitativa continua', 'cuantitativa discreta',
                 'cualitativa nominal', 'cuantitativa continua']}

variable_type_df = pd.DataFrame(data)
display(variable_type_df)

          Variable                   Tipo
0              age  cuantitativa discreta
1        workclass    cualitativa nominal
2           fnlwgt  cuantitativa discreta
3        education    cualitativa ordinal
4    education-num  cuantitativa discreta
5   marital-status    cualitativa nominal
6       occupation    cualitativa nominal
7     relationship    cualitativa nominal
8             race    cualitativa nominal
9              sex    cualitativa nominal
10    capital-gain  cuantitativa continua
11    capital-loss  cuantitativa continua
12  hours-per-week  cuantitativa discreta
13  native-country    cualitativa nominal
14          income  cuantitativa continua

## Análisis de valores faltantes

In [4]:
"""
Análisis de valores faltantes
"""
from ucimlrepo import fetch_ucirepo
from IPython.display import display
import pandas as pd
import numpy as np

adult = fetch_ucirepo(id=2)

X = adult.data.features
y = adult.data.targets

df = pd.concat([X, y], axis=1)

df.replace('?', np.nan, inplace=True)

print("Análisis de Valores Faltantes en el Dataset 'Adult'")
print("-" * 50)

# 1. Calcular el número de valores faltantes por columna
conteo_faltantes = df.isnull().sum()

# 2. Calcular el total de filas del DataFrame
total_filas = len(df)

# 3. Calcular el porcentaje de valores faltantes
porcentaje_faltantes = (conteo_faltantes / total_filas) * 100

# 4. Crear un DataFrame para mostrar los resultados de forma clara
resumen_faltantes = pd.DataFrame({
    'Conteo Faltantes': conteo_faltantes,
    'Porcentaje (%)': porcentaje_faltantes
})

# 5. Ordenar la tabla para ver las columnas más problemáticas primero
resumen_faltantes = resumen_faltantes.sort_values(by='Porcentaje (%)', ascending=False)

# 6. Filtrar para mostrar solo las columnas que SÍ tienen valores faltantes
resumen_faltantes = resumen_faltantes[resumen_faltantes['Conteo Faltantes'] > 0]

# 7. Imprimir el resultado final
if resumen_faltantes.empty:
    print("¡Felicidades! No se encontraron valores faltantes en el dataset.")
else:
    print(f"Resultados sobre un total de {total_filas} filas:\n")
    display(resumen_faltantes)

Análisis de Valores Faltantes en el Dataset 'Adult'
--------------------------------------------------
Resultados sobre un total de 48842 filas:

                Conteo Faltantes  Porcentaje (%)
occupation                  2809        5.751198
workclass                   2799        5.730724
native-country               857        1.754637

## Tratamiento de valores faltantes

Ya que los datos faltantes son mayores a un 5%, los vamos a tratar. Tenemos dos formas de hacerlo:

- **Imputación por constante**: Reemplazar "?" con una constante como "Desconocido"
- **Imputación por moda**: Reemplazar por la moda de esa columna

**Nos pareció mejor opción imputar por moda**

In [ ]:
# =================================================================
# Imputación con la Moda
# =================================================================

from IPython.display import display
from sklearn.impute import SimpleImputer
import pandas as pd

print("--- Imputación con la Moda ---")

# Creamos una copia del DataFrame original para no modificarlo
df_imputado_moda = df.copy()

# 2. Definimos las columnas que vamos a rellenar
columnas_a_imputar = ['workclass', 'occupation', 'native-country']

# 3. Creamos el imputador con la estrategia 'most_frequent'
imputador_moda = SimpleImputer(strategy='most_frequent')

# 4. Aplicamos el imputador
df_imputado_moda[columnas_a_imputar] = imputador_moda.fit_transform(df_imputado_moda[columnas_a_imputar])

print("\nMostrando el DataFrame imputado con la moda:")

display(df_imputado_moda)

--- Imputación con la Moda ---

Mostrando el DataFrame imputado con la moda:

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,Private,321403,HS-grad,9,Widowed,Prof-specialty,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

## Análisis Descriptivo